### ISSUE TITLE
Tests can only check non-interactive elements

### ISSUE THREAD

**Issue by jyn514** [charlesdaniels/bitshuffle#37] opened 2017-12-18 22:12 UTC
See https://github.com/charlesdaniels/bitshuffle/pull/34/files/a4ced202750988db4bc9e500697a9323eb20c6ce#r157613283 and https://github.com/charlesdaniels/bitshuffle/issues/31.  This is a long-term issue.

**Comment by charlesdaniels** [comment] 2017-12-18 22:14
This is a duplicate of #20

**Closed as completed** 2017-12-20 18:01 UTC
Labels: enhancement, hard, code quality
